Improve build
ForestryMC/Binnie pull request #10
Opened 2017-04-18 14:56 UTC by KorDum

Fix build config
Added README file with short instruction for build mod
Added Forge License
Add eclipse folder to gitignore

2017-04-18 17:34 UTC, marcin212 commented
What do you think @mezz?

2017-04-18 23:16 UTC, mezz requested changes
The script changes look good but some things need to change before it can be pulled.

2017-04-18 23:16 UTC, mezz commented on build.gradle
> +targetCompatibility = JavaVersion.VERSION_1_7
These should be Java 8, not 7.

2017-04-18 23:16 UTC, mezz commented on MinecraftForge-License.txt
> +Minecraft Forge Public Licence
Forge license is not required, we do not ship Forge.

2017-04-18 23:16 UTC, mezz commented on MinecraftForge-Credits.txt
> +* Eloraam *
Forge credits are not required, are not Forge.

2017-04-19 06:55 UTC, KorDum commented
Done. How can I assignment to reviewer automaticcaly without comment these?

2017-04-19 06:57 UTC, mezz commented
Just leave a comment like you just did, anyone reviewing will get a notification. I'll take a look.

2017-04-19 07:03 UTC, mezz approved these changes

2017-04-19 07:03 UTC, mezz commented
Looks good, tested and it set up a new 1.7.10 project correctly.

2017-04-19 07:04 UTC, merged