[1.7.10] Removed unfinished features
ForestryMC/Binnie pull request #118
Opened 2017-06-12 09:00 UTC by KorDum

Removed unused Honey Crystal
Removed unfinished kitchen machines
Removed Alcohol

2017-06-14 06:42 UTC, KorDum commented
@mezz do you want to publish on Curse the version first without this PR?

2017-06-14 08:09 UTC, lex1975 commented
Please don't remove item extrabees.item.scentedGear
Please don't remove unused liquids:
latex, sap, liquidnitrogen, poison, acid

These items and liquids can be used to create new recipes through CraftTweaker.

For example, I use this script:

# Squeezer. Create latex.
mods.forestry.Squeezer.addRecipe(<liquid:latex> * 1000, <Forestry:woodPulp:0> % 100, [<minecraft:log2:0>,<minecraft:log2:1>,<minecraft:log:2>], 20); 

#/ Foresry alveary block. Complication of recipe.
recipes.remove(<Forestry:alveary:0>);
mods.forestry.Carpenter.addRecipe(<Forestry:alveary:0>,
[[<Forestry:craftingMaterial:6>,<ExtraTrees:misc:3>,<Forestry:craftingMaterial:6>],
[<Forestry:craftingMaterial:6>,<Forestry:impregnatedCasing:0>,<Forestry:craftingMaterial:6>],
[<Forestry:craftingMaterial:6>,<ExtraBees:misc:0>,<Forestry:craftingMaterial:6>]],
<liquid:latex>*1000,20,null);

#/ ExtraTrees. Proven Gear. Complication of recipe.
recipes.remove(<ExtraTrees:misc:3>);
mods.forestry.Carpenter.addRecipe(<ExtraTrees:misc:3>,
[[null,<Forestry:oakStick:0>,null],
[<Forestry:oakStick:0>,<Forestry:beeswax:0>,<Forestry:oakStick:0>],
[null,<Forestry:oakStick:0>,null]],
<liquid:latex>*1000,20,null);

# Forestry Proven frame
recipes.addShaped(<Forestry:frameProven:0>,
[[<Forestry:oakStick:0>,<Forestry:oakStick:0>,<Forestry:oakStick:0>],
[<Forestry:oakStick:0>,<ExtraTrees:misc:3>,<Forestry:oakStick:0>],
[<Forestry:oakStick:0>,<Forestry:oakStick:0>,<Forestry:oakStick:0>]]);

# Foretry Proven grafter
recipes.addShaped(<Forestry:grafterProven:0>,
[[null,null,<ExtraTrees:misc:3>],
[null,<Forestry:oakStick:0>,null],
[<ExtraBees:misc:0>,null,null]]);

# Input Coolant Fluid - Binnie Liquid Nitrogen 0.0161mB/t).
mods.buildcraft.Fuels.addCombustionEngineCoolant(<liquid:liquidnitrogen>,2.0);

2017-06-14 08:14 UTC, KorDum commented
> Please don't remove item extrabees.item.scentedGear
> Please don't remove unused liquids:
> latex, sap, liquidnitrogen, poison, acid

Don't worry, it was not deleted.

2017-06-17 21:43 UTC, mezz requested changes

2017-06-17 21:43 UTC, mezz commented on README.md
> +This is an unofficial fork of mod.
This fork is official, Binnie gave me/us the rights to do it.

2017-06-17 21:44 UTC, mezz commented
I think this should be included in the upcoming release, I can mark it as an alpha for a week.

2017-06-18 06:28 UTC, KorDum commented on README.md
> +This is an unofficial fork of mod.
Fixed :)

2017-06-18 07:20 UTC, mezz approved these changes

2017-06-19 03:24 UTC, merged