Fix #238
ForestryMC/Binnie pull request #239
Opened 2017-08-03 15:27 UTC by SeraphJACK

2017-08-03 17:37 UTC, SeraphJACK commented
Add a few null-protections to fix #238 
I've already tested with @SihenZhang that it'll be fixed.

2017-08-03 18:38 UTC, KorDum commented
Please use codestyle and formatting from https://github.com/ForestryMC/Binnie/issues/123

2017-08-03 18:48 UTC, KorDum requested changes

2017-08-03 18:48 UTC, KorDum commented on src/main/java/binnie/genetics/item/ItemSerum.java
> +		return I18N.localise("genetics.item.serum.name");
It works without formatted args?

2017-08-04 06:07 UTC, closed without merging

2017-08-04 06:52 UTC, KorDum commented on src/main/java/binnie/genetics/item/ItemSerum.java
> +		return I18N.localise("genetics.item.serum.name");
`genetics.item.serum.name=%s Serum`