Create zh_CN,lang(s)
ForestryMC/Binnie pull request #334
Opened 2017-11-06 13:35 UTC by SihenZhang

Before merging, I want to let my friend @TartaricAcid and @3TUSK to have a check.

So sorry that because I'm not good at ExtraTrees and Botany, I can't translate them correctly.

2017-11-06 18:57 UTC, 3TUSK requested changes

2017-11-06 18:57 UTC, 3TUSK commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.errors.unknown.desc=这个错误已损坏，请将此反馈给mod作者
`这个错误已损坏`？

2017-11-06 18:57 UTC, 3TUSK commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.allele.forestry.effectAggressive.desc=进攻玩家
`攻击玩家`？

2017-11-06 18:57 UTC, 3TUSK commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.allele.extrabees.effect.ectoplasm.desc=产生外质蛛网状结构
`extrabees.block.ectoplasm.name=胶质网`

2017-11-06 18:57 UTC, 3TUSK commented on genetics/src/main/resources/assets/genetics/lang/zh_CN.lang
> +genetics.item.sequence.partially=部分测序 (%s%)
`%s%%` or game crashes with unknown formatter

2017-11-06 18:57 UTC, 3TUSK commented on genetics/src/main/resources/assets/genetics/lang/zh_CN.lang
> +bee.modifier.format.max=%.2fx (最大值： %.2fx)
Unnecessary extra space

2017-11-06 22:54 UTC, SihenZhang commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.errors.unknown.desc=这个错误已损坏，请将此反馈给mod作者
This error is broken.

机器会提示因为什么原因而不能运行，很明显这条就是用于一些非正常情况的

2017-11-06 22:55 UTC, SihenZhang commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.allele.forestry.effectAggressive.desc=进攻玩家
这是按照旧版翻译直接过来的，到时候改一下吧

2017-11-07 11:29 UTC, SihenZhang commented on genetics/src/main/resources/assets/genetics/lang/zh_CN.lang
> +genetics.item.sequence.partially=部分测序 (%s%)
然而en_US.lang就是这样的

2017-11-08 08:24 UTC, 3TUSK commented on genetics/src/main/resources/assets/genetics/lang/zh_CN.lang
> +genetics.item.sequence.partially=部分测序 (%s%)
@mezz I believe that `%s)` can [crash the game](https://docs.oracle.com/javase/8/docs/api/java/util/UnknownFormatConversionException.html)... will that even work?

2017-11-08 08:25 UTC, TartaricAcid approved these changes

2017-11-08 08:27 UTC, 3TUSK commented on core/src/main/resources/assets/binniecore/lang/zh_CN.lang
> +binniecore.errors.unknown.desc=这个错误已损坏，请将此反馈给mod作者
未知错误，请反馈给 mod 作者？

2017-11-12 04:14 UTC, 3TUSK approved these changes
This can be merged now.

2017-11-12 05:11 UTC, mezz commented
Thank you!

2017-11-12 05:12 UTC, merged