Create ru_RU.lang
ForestryMC/Binnie pull request #353
Opened 2017-11-24 10:41 UTC by Mr-Krab

binniecore

2017-11-24 12:32 UTC, KorDum commented
I will oversee this translation.

2017-11-24 12:33 UTC, KorDum requested changes

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootBees.epitome.6=Избранный Сенгир
Думаю, `Sengir's Chosen` Переводится как "Выбор Sengir'а".

Так как Sengir — один из основателей Forestry, его ник детранслитирировать не нужно.

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootBees.chromosome.never_sleeps.short=Cathemeral
Пропущено слово?

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootButterflies.chromosome.nocturnal.short=Cathemeral
Пропущено слово?

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootBees.chromosome.never_sleeps.short=Cathemeral
Оно означает "работу ночью" или "работу в подземельях"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.none=None
Нужно посмотреть, как переведено это в Forestry. Возможно подойдет прочерк.

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.breedingmessage.branch=Обнаруженные филиалы
Филиалы? Это же "ветви" спецфикации.

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.item.container.can=Можно
"Капсула", а не "можно"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.errors.task.cancelled.info=Отменена постройка ворот
Каких ворот? о_О

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.errors.unknown.desc=Эта ошибка не работает, сообщите об этом авторам мода
"Эта ошибка не работает" => "Неизвестная ошибка"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.database.branch.branch=Филиал
Ветвь

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.database.branch.name=%s Филиал
`Ветвь %s`

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.database.discovered.undiscovered=Не обнаруженные виды
"Необнаруженные" слитно

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.fieldkit.info=Полевой комплект анализирует пчел, деревья, цветы и бабочек. Все что требуется - это кусочек бумаги для заметок.
"Все, что потребуется, -"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.forestry.effectDrunkard.desc=Причины игроков хмелеть
Что?

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.extrabees.effect.hunger.desc=Заставляет игроков стать голодными
"Заставляет игроков голодать"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.extrabees.effect.meteor.desc=Заставляет метеориты падать с неба.
Точку в конце убрать

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.extrabees.effect.power.desc=Обеспечивает некоторую мощность для машин
"Заряжает машины" звучит лучше?

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.forestry.effectRepulsion.desc=Естественно спавнит мобов, что бы избежать этого
Что?

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.help.desc=Чтобы активировать подсказки, удерживайте %s и наведите указатель мыши на элементы управления..
Две точки в конце убрать

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.process=Технологический слот
"Слот обработки", он не технологический.

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.polish=Польский слот
Какой "польский"? "Пыльца"!

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.caterpillar=Слот условного шва
Это переводится как "Затирка"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.analyse=Анализ слота
"Слот анализа"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.wood=Деревянный слот
"Слот для дерева"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.incubator=Слот для инкубатора
"Слот инкубации"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.serum.input=Входная слот сыворотки
"Входящая сыворотка"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.serum.output=Выходной слот сыворотки
"Выходящая сыворотка"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.serum.active=Активный слот сыворотки
"Активная сыворотка"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.slot.yeast=Слот дрожжей
"для"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.side.insert=Вставить сторону: %s
"Входящие стороны:"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.gui.side.extract=Извлечь сторону: %s
"Выходящие стороны:"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.side.none=None
"Нет"

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.key.hold.for.help.tooltips=Удерживайте для отображения справки
"Удерживайте КНОПКА для отображения..."

2017-11-24 12:33 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +#Перевел Mr_Krab для проекта mc.beandex.ru
Это не нужно в файле локализации мода

2017-11-24 12:36 UTC, Mr-Krab commented
Переводил с помощью гугла. Местами перевод от яндекса. Могут быть ошибки. Если нашли, прошу поправить.

2017-11-24 12:38 UTC, KorDum commented
Спасибо за работу!
Я отписал в комментариях все, что нашел в этом файле, можно поправить прямо по ним.

2017-11-24 12:41 UTC, Mr-Krab commented
Я сегодня еще доработал перевод Forestry для 1.12.2, но вот скинуть его на официальный репозиторий не смог. Почему-то заблокирована там такая возможность. Языковый строки привел к одному виду с англоязычным файлом, переведен только текст, за основу взял оригинальный перевод и дополнил его.

2017-11-24 12:44 UTC, KorDum commented
По поводу перевода в Forestry: создайте в том репозитории issue с вопросом, почему так. Я, к сожалению, нахожусь в команде только этого мода :)

2017-11-24 22:23 UTC, mezz commented
Thank you both. Please mention me when these are ready and I will pull them.

2017-11-25 08:07 UTC, KorDum commented
@mezz Thank you! Since there are a lot of inaccuracies and machine translation in the text, it'll not be soon...

2017-11-25 08:19 UTC, KorDum commented
@Mr-Krab советую посмотреть на перевод для 1.7.10:
https://github.com/ForestryMC/Binnie/tree/master-MC1.7.10/src/main/resources/assets

2017-12-04 07:00 UTC, KorDum requested changes
Еще вот это заметил. И остался комментарий с "None" с предыдущего раза.

2017-12-04 07:00 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootTrees.chromosome.yield=Уступание
Это переводится как "урожай"

2017-12-04 07:00 UTC, KorDum commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.rootTrees.chromosome.yield.short=Уступание
"Урожай"

2017-12-04 07:01 UTC, Mr-Krab commented
Сейчас исправим.

2017-12-04 07:06 UTC, Mr-Krab commented on core/src/main/resources/assets/binniecore/lang/ru_RU.lang
> +binniecore.allele.none=None
В Forestry переводится как "Нет"

2017-12-04 07:07 UTC, Mr-Krab commented
Обновил.

2017-12-04 07:08 UTC, KorDum approved these changes

2017-12-04 07:08 UTC, KorDum commented
@Mr-Krab thanks for work!
@mezz all done :)

2017-12-05 06:04 UTC, mezz commented
Thank you!

2017-12-05 06:04 UTC, merged