Create ru_RU.lang
ForestryMC/Binnie pull request #356
Opened 2017-11-24 10:44 UTC by Mr-Krab

Binniedesign

2017-11-24 12:33 UTC, KorDum commented
I will oversee this translation.

2017-11-25 08:09 UTC, KorDum requested changes

2017-11-25 08:09 UTC, KorDum commented on design/src/main/resources/assets/binniedesign/lang/ru_RU.lang
> +binniedesign.pattern.overlapped.split.barred=Перекрытое разделение скрещивания
Перекрытое разделение со скрещиванием

2017-12-04 07:02 UTC, KorDum approved these changes

2017-12-04 07:02 UTC, KorDum commented
@Mr-Krab thanks for hardwork!
@mezz all done for merge :)

2017-12-05 06:04 UTC, mezz commented
Thank you!

2017-12-05 06:04 UTC, merged