Create ru_RU.lang
ForestryMC/Binnie pull request #357
Opened 2017-11-24 10:46 UTC by Mr-Krab

Extratrees

2017-11-24 12:33 UTC, KorDum commented
I will oversee this translation.

2017-11-25 08:05 UTC, KorDum requested changes

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +#Перевел Mr_Krab для проекта mc.beandex.ru
Это следует убрать из файла локализации

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.machine.machine.brewery.info=Пивоварня использует дрожжи, соки и зерна, чтобы сделать много видов вин и пива.
"...для производства множества видов..."

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.errors.brewery.no.recipe.desc=Пивоварение не может произойти с этими ингредиентами
"Нельзя сварить, используя эти ингредиенты"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.machine.machine.press.info=Фруктовый пресс сжимает фрукты, чтобы давать различные фруктовые соки. Его можно запустить с помощью питания или вручную, щелкнув правой кнопкой мыши.
"...для производства различных фруктовых соков"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.machine.machine.lumbermill.info=Лесопилка преобразует бревна в доски с увеличенной скоростью и производит побочные продукты, такие как опилки и кора.
"распиливает бревна на доски"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.machine.machine.woodworker.info=Деревообделочный станок создает узорную деревянную черепицу из двух разных пород дерева.
"Деревообрабатывающий"! Обделываются по другому поводу :D

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.fir=Пихта
Вот это все, кажется, нужно переводить как "из пихты", чтобы в итоге получилось "доски из пихты". Советую посмотреть на перевод этого в 1.7.10 версии.

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.whitebeam.desc=Несмотря на название рябина ария имеет довольно приглушенный цвет.|Лесоруб Джек
"Несмотря на название," - запятая

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.apple.desc=Очень темное дерево, делает яблоки очень полезного сорта.|Лесоруб Джек
Не "делает", а "дает"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.brazilwood.desc=Бразильский лес известен своим глубоким фиолетовым оттенком.|Лесоруб Джек
"Бразильское дерево"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.logwood.desc=Кампеш является одним из самых близких, вы можете добраться до красной древесины.|Лесоруб Джек
Что?

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.iroko.desc=Эта привлекательная тёмная древесина сделает прекрасную перемычку.|Лесоруб Джек
Что?

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.purpleheart.desc=Глубокий оттенок фиолетового делает это дерево метко названным.|Лесоруб Джек
"Глубокий оттенок фиолетового делает это дерево метко названным" => "Название этого дерева как нельзя кстати подходит под его глубокий оттенок фиолетового"

А то как-то не по-русски.

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.holly.desc=Белейшая древесина доступна, просто избегайте острых листьев, чтобы добраться до нее.|Лесоруб Джек
Что?

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.rosewood.desc=Используется для изготовления шахматных фигур, это еще одна сильнотованная древесина.|Лесоруб Джек
Что такое "сильнотованная"?

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.database.arborist.master.tooltip=Сенгир в банке
Не нужно детрансилитировать Sengir'а, это ник одного из основателей Forestry

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
?

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extrabees.glacial.name=Лед.
Точка не нужна

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.gui.database.tab.fruit.potential.help=Список деревьев, которые могут производить этот плод, если они обладают правом аллели
", если они имеют соответcтвующий ген"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.gui.database.tab.wood.natural.help=Список деревьев, которые сделаны из этой древесины
"которые имеют эту древесину"

2017-11-25 08:05 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.gui.database.tab.planks.natural.help=Список деревьев, которые производят бревна из которых могут быть созданы эти доски
Запятая перед "из которых". И деревья не могут производить бревна

2017-11-25 08:17 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.fir=Пихта
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/resources/assets/extratrees/lang/ru_RU.lang#L41

2017-12-03 15:36 UTC, Mr-Krab commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.logwood.desc=Кампеш является одним из самых близких, вы можете добраться до красной древесины.|Лесоруб Джек
Сам не понимаю бреда переводчика, пока оставлю так.

2017-12-03 15:43 UTC, Mr-Krab commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
Я без понятия как это перевести. Переводчики которые я использую тоже этого не знают...

2017-12-04 07:10 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
"Дрожжевой лаг" - если не ошибаюсь. Это когда дрожжи находятся в лаг-фазе.

2017-12-04 07:11 UTC, Mr-Krab commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
Хорошо, поставим такой перевод.

2017-12-04 07:28 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
Загоняешь в гугл и видишь, что это "Адамово яблоко"

2017-12-04 07:30 UTC, Mr-Krab commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
Мне гугл перевел как Осейдж Оранж. Хотя может надо было поискать лучше. Добавим сейчас.

2017-12-04 07:47 UTC, KorDum commented on extratrees/src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.item.yeast_lager.name=Lager LagerYeast
Я имел в виду гугл, а не гугл переводчик =)
Гугл выдает ссылку на вики.

2017-12-04 07:48 UTC, KorDum approved these changes

2017-12-04 07:48 UTC, KorDum commented
@Mr-Krab thanks for hardwork!
@mezz all done!

2017-12-05 06:05 UTC, merged