Create ru_RU.lang
ForestryMC/Binnie pull request #358
Opened 2017-11-24 10:47 UTC by Mr-Krab

Genetics

2017-11-24 12:33 UTC, KorDum commented
I will oversee this translation.

2017-11-25 07:48 UTC, KorDum requested changes

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.errors.no.owner.desc=Замените этот блок, чтобы получить эту машину
Тут имеется в виду, что по каким-то причинам у машины пропал владелец и надо "переустановить" ее. Думаю, имеет смысл перевести как `Нет владельца, переустановите блок`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.errors.defunct.serum.desc=Человек уже обладает этой аллелью
Не человек, а `сущность` или `индивид`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.machine.isolator.info=Изолятор занимает случайную аллель от пчелы, дерева или другого индивида и копирует его в пустой флакон последовательности. Это требует использования этанола в
"Изолятор занимает случайную аллель от пчелы" => "Изолятор изолирует случайный ген индивида". Так как он работает не только с пчелами.

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.errors.isolator.no.empty.sequencer.desc=Нет свободных флаконов секвенсора
`Нет пустых флаконов для секвенции`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.machine.sequencer.info=Секвенсор берет необнаруживаемые сыворотки и определяет, какая аллель присутствует в них. Этот процесс медленный и требует использования флуоресцентного красит
"Секвенсор берет необнаруживаемые сыворотки и определяет" => "Секвенсор заряжает сыворотки и изучает, какой ген присутствует в них"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.machine.sequencer.texts.userless=Пользователь. Не будет сохранять последовательности
"Нет владельца. Последовательности не будут сохранены"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.lab_machine.genepool.info=Генофонд использует ферменты и этанол, чтобы сломать ДНК живых существ. В ходе этого процесса вся генетическая информация теряется и источник ДНК уничтожает
`чтобы сломать ДНК живых существ` => `чтобы запомнить ДНК живых существ`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.lab_machine.analyser.info=Анализатор принимает селекционные индивидуумы и секвенсоры ДНК и анализирует их для того чтобы определить присутствующие гены. Для этого требуется ДНК-краск
"Анализатор принимает селекционные индивидуумы и секвенсоры ДНК и анализирует их для того чтобы определить присутствующие гены. Для этого требуется ДНК-краска, созданная из фиолетовой краски и светящегося камня" => "Анализатор принимает индивидуумы и секвенсоры ДНК и анализирует их для того, чтобы определить присутствующие гены. Для этого требуется ДНК-краска, созданная из фиолетовой краски и светящегося камня"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.lab_machine.incubator.info=Инкубатор сочетает в себе жидкости и предметы и позволяет им сидеть при идеальной температуре, чтобы стимулировать рост бактерий.
Не "сидеть", а "находиться"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.adv_machine.splicer.tooltips.slots.serum=Сыворотка пробирки и массивы
"Сыворотка и массивы сывороток"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.machine.adv_machine.splicer.tooltips.slots.individual=Соединенный индивид
Просто "Индивид"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.desc=Добавьте пчелу, дерево, цветок или бабочку в верхний левый слот. Краска ДНК необходима, если она еще не была проанализирована. Этот краситель также может конвертировать вани
"Добавьте пчелу, дерево, цветок или бабочку в верхний левый слот. Краска ДНК необходима, если она еще не была проанализирована. Этот краситель также может конвертировать ванильные элементы в селекционные особи." => "Добавьте пчелу, саженец дерева, цветок или бабочку в верхний левый слот. Краска ДНК необходима, если индивид еще не был проанализирован. Этот краситель также может конвертировать ванильные саженцы в селекционные виды."

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.products.centrifuges=Центрифуги, которые должны давать
"Продукция в центрифуге"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.products.natural=Природные соединения
"Основная продукция"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.products.specialty=Специализированная продукция
"Специальная продукция"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.products.squeezes=Сжимает, чтобы дать
Продукция в соковыжималке

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.wood.noFruits=Это дерево не имеет \n фруктов или орехов
Пере `\n` и осле пробелы не нужны

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.growth.mature=Саженцы созревают в
"Время созревания"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.analyst.fruit.noFruits=Это дерево не имеет \n фруктов или орехов
Перед и после `\n` пробелы не нужны

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.item.gene.charge=Сбор
"Заряд"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.item.gene.charges=Сборы
"Заряды"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.item.gene.more.genes=больше генов. Удерживайте Shift для отображения.
Не надо слова "больше"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +bee.modifier.format.max=%.2fx (Max: %.2fx)
`Макс:`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +bee.modifier.format.min=%.2fx (Min: %.2fx)
`Мин:`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +extrabees.block.advGeneticMachine.name=Продвинутаягенетическая Машина
"Продвинутая генетическая машина"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +extrabees.genetics.quality.good=ороший
"Хороший"

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +extrabees.genetics.quality.tooltip=%s Качество
Из-за особенностей отображения следует написать так `Качество: %s`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.database.tab.species.genome.extrabees.sunlight=Солнечный лучик:
о_О `Дневной свет`

2017-11-25 07:48 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +genetics.gui.database.tab.species.overview=Озор
"Обзор"

2017-11-25 07:48 UTC, KorDum commented
Очень много опечаток и машинного перевода :(

2017-11-25 07:51 UTC, KorDum requested changes

2017-11-25 07:51 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +#Перевел Mr_Krab для проекта mc.beandex.ru
Это следует убрать из файла локализации.

2017-12-04 07:05 UTC, KorDum requested changes
Все хорошо, кроме проигнорированного одного комментария.

https://github.com/ForestryMC/Binnie/pull/358/files/c36338587205ab9777e141908616dc35b422f3ec..f20060748d7b8ce9aa865c705b9f4b6d95720e9e#diff-aa06e745e5863c2878865cca1f601671L256

2017-12-04 07:05 UTC, KorDum commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +extrabees.genetics.quality.tooltip=%s Качество
А это почему было проигнорировано?

2017-12-04 08:19 UTC, KorDum commented
Остается тут мелочь и все готово :)

2017-12-04 08:22 UTC, Mr-Krab commented on genetics/src/main/resources/assets/genetics/lang/ru_RU.lang
> +extrabees.genetics.quality.tooltip=%s Качество
Проглядел. Сейчас сделаем.

2017-12-04 08:31 UTC, KorDum approved these changes

2017-12-04 08:31 UTC, KorDum commented
@Mr-Krab thanks!
@mezz all done

2017-12-05 06:06 UTC, merged