Validate ItemFieldKit to avoid metadata manipulations with items
ForestryMC/Binnie pull request #375
Opened 2017-12-25 07:22 UTC by Sirse

Validate ItemFieldKit to avoid metadata manipulations with items, putted in held slot alongside GUI FieldKit are opened.

This is unfinished fix, held slot should be locked from manipulations like Forestry do it (look into backpack code, e.g).

2017-12-25 14:32 UTC, KorDum requested changes

2017-12-25 14:32 UTC, KorDum commented on src/main/java/binnie/core/craftgui/WindowFieldKit.java
> +			if(kit == null || !kit.getItem().equals(BinnieCore.fieldKit)) {
Please keep codestyle
```
if (...
```

2017-12-27 04:53 UTC, mezz commented
Thanks! I will accept this as-is because it is a public exploit. We can fix formatting later.

2017-12-27 04:53 UTC, merged

2017-12-27 19:44 UTC, 3TUSK commented
@mezz Any chance for this being cherry-picked to `master-MC1.12.2`? I have encountered the same issue in my 1.12.2 pack, which makes Portable Analyzer have damage value of 64 and thus have a purple-black "missing model".

Steps to reproduce:
1. Binnie 2.5.0.107 is used.
2. Fill Field Kit with some paper (less than 64).
3. While opening Field Kit GUI, use number key to swap Field Kit and Portable Analyzer.

Screenshot after the swap is provided below. You can notice that Portable Analyzer has a "missing model" model.
![2017-12-24_15 20 47](https://user-images.githubusercontent.com/9113033/34391342-d7ffdbf6-eaf9-11e7-94f6-2e0e8fafa483.png)

Using MCEdit, it is discovered that Portable Analyzer got a damage value of 64 after the swap. Changing it to 0 does resolve the issue.
> Might consider doing `setMaxDamage(0)` for `ItemAlyzer`?

2017-12-27 22:49 UTC, mezz commented
@3TUSK thanks, cherry-picked to on 1.12 now.
Even if the analyzer had a max damage set, this code would still override it. It really wasn't checking anything at all.