Improve research catalysts
ForestryMC/Binnie pull request #439
Opened 2018-03-15 04:59 UTC by RusTit

@mezz @Nedelosk please review.
But that's not all that needs to be done.
It is also necessary to register in botany.
https://github.com/ForestryMC/Binnie/blob/d503530df2762518559a0c97b5ab44e70dcb0146/botany-api/src/main/java/binnie/botany/api/BotanyAPI.java#L11
Currently there are no dependencies between them directly.
How should I do it right? Add a dependency or somehow programmatically check the load of the module? Or somehow?

2018-03-15 05:01 UTC, RusTit commented
Related to https://github.com/ForestryMC/ForestryMC/issues/2034

2018-03-15 16:42 UTC, temp1011 commented
Use this to check if modules are loaded:
https://github.com/ForestryMC/ForestryMC/blob/2ce018d84b42518ed82a5a3e5fe374c88b325a9a/src/main/java/forestry/api/core/ForestryAPI.java#L90

2018-03-15 16:46 UTC, Nedelosk commented
We only create a instance of a root if the module is enabled. So you only have to check if the value is null.

2018-03-17 22:14 UTC, RusTit commented
Please review.

2018-03-17 22:39 UTC, Nedelosk requested changes

2018-03-17 22:39 UTC, Nedelosk commented on extrabees/src/main/java/binnie/extrabees/items/ItemHoneyComb.java
> +		TreeManager.treeRoot.setResearchSuitability(new ItemStack(this, 1, OreDictionary.WILDCARD_VALUE), RESEARCH_SUITABILITY);
`TreeManager.treeRoot` and `ButterflyManager.butterflyRoot` are null if the module that adds them is disabled. Please add a null check.

2018-03-17 23:12 UTC, RusTit commented
Please review.

2018-03-17 23:29 UTC, Nedelosk approved these changes

2018-03-17 23:29 UTC, merged