Add version tag stub.
ForestryMC/Binnie pull request #441
Opened 2018-03-15 23:51 UTC by RusTit

Added a tag with a version for submods.
(As already done with BinnieCore)
https://github.com/ForestryMC/Binnie/blob/d503530df2762518559a0c97b5ab44e70dcb0146/core/src/main/java/binnie/core/BinnieCore.java#L59-L67
But I also found that after the build of the jar the tag is not set
After de-compile:
```
@Mod(
    modid = "binniecore",
    name = "Binnie Core",
    version = "unspecified",
    acceptedMinecraftVersions = "[1.12.2,1.13)",
    dependencies = "required-after:forge@[14.23.1.2555,);required-after:forestry@[5.7.0.214,);after:jei@[4.7.8,);"
)
```
It would be nice to fix this, too.

2018-03-15 23:53 UTC, RusTit commented
This should remove from the log messages with a warning:
```
[09:43:53] [main/WARN]: Mod botany is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[09:43:54] [main/WARN]: Mod binniedesign is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[09:43:54] [main/WARN]: Mod extrabees is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[09:43:54] [main/WARN]: Mod extratrees is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[09:43:54] [main/WARN]: Mod genetics is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
```

2018-03-16 04:20 UTC, mezz requested changes

2018-03-16 04:20 UTC, mezz commented on botany/src/main/java/binnie/botany/Botany.java
> +    version = "@VERSION@",
please fix indentation

2018-03-16 04:23 UTC, mezz approved these changes

2018-03-16 04:24 UTC, merged

2018-03-16 04:26 UTC, RusTit commented
But I also found that after the build of the jar the tag is not set
After de-compile:
@Mod(
    modid = "binniecore",
    name = "Binnie Core",
    version = "unspecified",
    acceptedMinecraftVersions = "[1.12.2,1.13)",
    dependencies = "required-after:forge@[14.23.1.2555,);required-after:forestry@[5.7.0.214,);after:jei@[4.7.8,);"
)
Can you suggest something about this?

2018-03-16 04:41 UTC, mezz commented
We might need to move this section higher in the `build.gradle`:
```groovy
    version = version_major + '.' + version_minor + '.' + version_patch
    if (System.getenv("BUILD_NUMBER") != null) {
        version = version + "." + System.getenv("BUILD_NUMBER")
    }
```
so it's before 
`replace '@VERSION@', project.version`

I'm not completely sure though.