Clean Up
ForestryMC/Binnie pull request #472
Opened 2018-03-24 14:37 UTC by temp1011

Mainly removing decompile artifacts. It looks like there are a lot of unused trees in the world gen section that might need cleaning up. There also seems to be a lot of reused code but I'm not sure of a nice way to reduce it.

2018-03-24 19:24 UTC, mezz requested changes
Looks pretty good, just some minor requests.

2018-03-24 19:24 UTC, mezz commented on extrabees/src/main/java/binnie/extrabees/alveary/AlvearyLogicFrameHousing.java
> +			return (IHiveFrame) getFrameStack().getItem();
For situations like this, I like to store the result of `getFrameStack()` to a value so it is not called twice.

- Slightly better performance, any method call like `getFrameStack()` may do some calculation.
- Static analysis will work when it's trying to figure out if the `.getItem()` call is null-safe. As far as the analyzer knows, the result of `getFrameStack()` might be different each time it's called.

2018-03-24 19:24 UTC, mezz commented on extrabees/src/main/java/binnie/extrabees/alveary/AlvearyLogicFrameHousing.java
> +	private ItemStack getFrameStack() {
The preferred way of handling `ItemStack` in 1.12 and higher is never have them be `@Nullable`.
Most of the time you might use `null` to signify a missing `ItemStack`, it's better to use an empty one instead.
That way we are not checking for `!= null` and `!itemStack.isEmpty()` every time we use an `ItemStack`.

2018-03-26 20:29 UTC, temp1011 commented
Hopefully this sorts this out. Sorry for slow response.

2018-03-27 04:10 UTC, mezz approved these changes
Thanks, looks good!

2018-03-27 04:10 UTC, merged