Add Binnie's hive generation to the Forestry HiveRegistry
ForestryMC/Binnie pull request #486
Opened 2018-03-27 23:46 UTC by temp1011

Adds Binnie hive generation to forestry `HiveRegistry` so that binnie hives will obey forestry configs (eg - for dimension blacklisting.

Still TODO:
- figure out why this seems to get stuck sometimes
- expose getting the instance of `HiveRegistry` in Forestry
- Make this faster  (worldgen is very slow).

Hopefully it is possible to do this without it being too slow. I'm sure there's a lot that can be done to help that.

2018-03-28 04:37 UTC, mezz requested changes

2018-03-28 04:37 UTC, mezz commented on extrabees/src/main/java/binnie/extrabees/worldgen/WorldGenHiveMarble.java
> +			pos.add(0, -1, 0);
The strategy here will check every block from the surface down to 0.
A more efficient strategy would be to get the  `topPos` and try a few random locations between 0 and `topPos`.
Only try a few locations before giving up.

2018-03-28 11:17 UTC, temp1011 commented
Still needs tweaks to get worldgen to previous levels. Also, the rate registered with forestry should depend on the config settings for extrabees.

2018-03-29 06:06 UTC, KorDum commented on extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java
> +		if (hiveType == EnumHiveType.NETHER) {
You can simplify this
```java
return hiveType != EnumHiveType.NETHER
    || BiomeDictionary.hasType(biome, BiomeDictionary.Type.NETHER);
```

2018-03-29 14:56 UTC, temp1011 commented on extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java
> +		if (hiveType == EnumHiveType.NETHER) {
Thanks

2018-03-29 15:07 UTC, temp1011 commented
![2018-03-29_16 06 09](https://user-images.githubusercontent.com/34900092/38096626-47707626-336b-11e8-96b9-478b8765f757.png)
Current gen with hive debug on.

2018-04-10 22:39 UTC, temp1011 commented
I'm still not sure if the rates are right. Also, I think marble hives were designed for Red Power 2 marble so don't generate as frequently on chisel marble. I will include some issues I think this resolves:
Closes https://github.com/ForestryMC/Binnie/issues/459
Closes https://github.com/ForestryMC/Binnie/issues/424
Closes https://github.com/ForestryMC/Binnie/issues/393 (as far as I am aware no trees generate in the nether and Forestry does not have cascading issues)
Closes https://github.com/ForestryMC/Binnie/issues/301 (similarly I don't think trees generate in the deep dark)
Note there is still an issue open for cascading worldgen in https://github.com/ForestryMC/Binnie/issues/315 which needs the forge PR to solve.

2018-04-12 19:26 UTC, mezz commented
Whenever I've done tweaks to hive generation, I add some debug logging for how many of each hive are placed.
Start a new world and fly forward for a specific distance and see how many of each hive were placed. Recreate the world with the same seed and do the same thing with your changes applied, and tweak the values until they are close.

2018-04-13 12:41 UTC, AnrDaemon commented
> as far as I am aware no trees generate in the nether

[You would be surprized…](https://minecraft.curseforge.com/projects/natura)

2018-04-13 15:06 UTC, Nedelosk commented
@AnrDaemon He talks about trees from extra trees.

2018-06-20 12:35 UTC, Nedelosk commented
What's the current state of this PR ?

2018-06-20 12:36 UTC, temp1011 commented
I haven't looked at it in a while sorry. I need to test the numbers to make sire everything works the same. Not sure how good this is for performance as well.

2018-06-21 00:34 UTC, acanady commented
Oh great though I just couldn't find them, turns out they weren't generating at all to begin with

2018-06-27 00:50 UTC, temp1011 commented
The bee effect coming off the hives is the wrong colour at the moment too (I get forest bees for rocky hives).

2018-07-17 11:48 UTC, temp1011 commented
I can hopefully get this done this Sunday. At the moment it's difficult for me to test it though.

2018-11-09 14:56 UTC, Nedelosk commented
@temp1011 Any update ?

2018-11-09 14:57 UTC, temp1011 commented
I believe this needs https://github.com/ForestryMC/ForestryMC/pull/2204 to work well, but I haven't looked at this in a while.

2019-01-14 23:10 UTC, temp1011 commented
See new PR

2019-01-14 23:10 UTC, closed without merging