Feature/refactoring
ForestryMC/Binnie pull request #77
Opened 2017-05-23 09:00 UTC by KorDum

Some code cleanup.
Remove some unused classes and methods.

2017-05-23 09:33 UTC, KorDum commented
Hmm. Travis didn't even get to the build.

2017-05-24 06:11 UTC, mezz requested changes

2017-05-24 06:11 UTC, mezz commented on src/main/java/binnie/core/gui/BinnieCoreGUI.java
> +import binnie.botany.craftgui.WindowFieldKit;
this import change here broke the travis build

2017-05-24 06:44 UTC, KorDum commented
Fixed, thanks.

2017-05-24 06:52 UTC, mezz commented on src/main/java/binnie/core/machines/RendererMachine.java
> +// Hmm. It's used class
This is not a very good comment...

2017-05-24 06:52 UTC, mezz commented on src/main/java/binnie/core/triggers/TriggerWorking.java
> -public class TriggerWorking {
I think these triggers are supposed to be used by BuildCraft logic gates, are you sure they do not work?

2017-05-24 06:54 UTC, mezz approved these changes

2017-05-24 06:55 UTC, KorDum commented on src/main/java/binnie/core/triggers/TriggerWorking.java
> -public class TriggerWorking {
Without implementing some BuildCraft API interfaces?
Need to check it, of course. I'll check during the day.

2017-05-24 06:56 UTC, mezz commented on src/main/java/binnie/core/triggers/TriggerWorking.java
> -public class TriggerWorking {
Yeah I guess it was never complete. I will merge this.

2017-05-24 06:57 UTC, KorDum commented on src/main/java/binnie/core/machines/RendererMachine.java
> +// Hmm. It's used class
IDEA says that class is unused. But if drop it, genetic machines aren't render o_O
Many strange code...

2017-05-24 06:58 UTC, merged