Fix drop doors after break
ForestryMC/Binnie pull request #8
Opened 2017-04-12 18:27 UTC by KorDum

Fix drop doors after break
Improve code code readability

2017-04-16 13:21 UTC, Elec332 commented
oops, wrong button

2017-04-18 13:10 UTC, marcin212 requested changes

2017-04-18 13:10 UTC, marcin212 commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +	public IIcon getIcon(final IBlockAccess par1IBlockAccess, final int x, final int y, final int z, final int par5) {
```java
final IBlockAccess par1IBlockAccess
```
Could you change this to: blockAccess

2017-04-18 13:10 UTC, marcin212 commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +	public int colorMultiplier(final IBlockAccess par1IBlockAccess, final int x, final int y, final int z) {
and here

2017-04-18 13:10 UTC, marcin212 commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +	public int getFullMetadata(final IBlockAccess par1IBlockAccess, final int x, final int y, final int pzr4) {
same here

2017-04-18 13:10 UTC, marcin212 commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +		return BlockMetadata.getBlockDropped(this, world, x, yCoord, z, blockMeta);
Did you test it?

2017-04-18 15:12 UTC, KorDum commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +		return BlockMetadata.getBlockDropped(this, world, x, yCoord, z, blockMeta);
Yes. Door drops correctly if you cut it from up block or down block.

2017-04-18 15:15 UTC, KorDum commented
I made some changes to the code.
Do I need to create the pool request again?

2017-04-18 16:04 UTC, KorDum commented on src/main/java/binnie/extratrees/block/BlockETDoor.java
> +		return BlockMetadata.getBlockDropped(this, world, x, yCoord, z, blockMeta);
I tested with different doors: from different materials and different metas.

2017-04-18 17:27 UTC, marcin212 approved these changes

2017-04-18 17:31 UTC, merged

2017-04-19 07:04 UTC, mezz commented
Please check if this needs to be done for the 1.11.2 version as well