Update en_US.lang
ForestryMC/Binnie pull request #93
Opened 2017-06-03 21:31 UTC by lex1975

Added some localization. One bug fixed

2017-06-04 06:07 UTC, KorDum commented
https://github.com/ForestryMC/Binnie/pull/94#discussion_r120001280

2017-06-04 06:08 UTC, KorDum requested changes

2017-06-04 06:08 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/en_US.lang
> +# extratrees.block.planks.pinkivory=Pink Ivory
https://github.com/ForestryMC/Binnie/pull/94#discussion_r120001280

2017-06-04 15:51 UTC, lex1975 commented on src/main/resources/assets/extratrees/lang/en_US.lang
> +# extratrees.block.planks.pinkivory=Pink Ivory
It is right key (With a space):
extratrees.block.planks.pink ivory=Pink Ivory
I believe that this line is not needed:
extratrees.block.planks.pinkivory=Pink Ivory
Maybe I'm wrong.

2017-06-05 06:43 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/en_US.lang
> +# extratrees.block.planks.pinkivory=Pink Ivory
Please remove this change and I merge PR.

2017-06-05 07:16 UTC, KorDum requested changes

2017-06-05 07:16 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/en_US.lang
> +extratrees.block.planks.pink ivory=Pink Ivory
This is wrong key. Need without space.
See screenshot below.
https://cloud.githubusercontent.com/assets/1331559/26763298/558b19f2-4959-11e7-9ef2-6889bc20705c.png

2017-06-05 07:24 UTC, merged

2017-06-05 07:24 UTC, KorDum commented
Thanks!