Update ru_RU.lang
ForestryMC/Binnie pull request #94
Opened 2017-06-03 21:33 UTC by lex1975

Added some localization. One bug fixed

2017-06-04 06:07 UTC, KorDum requested changes

2017-06-04 06:07 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
> +# extratrees.block.planks.pinkivory=умнини
Why do you commented it?
Localization key is right.

2017-06-04 07:34 UTC, KorDum commented
Can you add RUS localization for https://github.com/KorDum/Binnie/blob/33f985c2e7c363554cdbd81a1f15d21e66ebea92/src/main/resources/assets/botany/lang/en_US.lang#L16-L123 ?

2017-06-04 15:51 UTC, lex1975 commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
> +# extratrees.block.planks.pinkivory=умнини
It is right key (With a space):
extratrees.block.planks.pink ivory=умнини
I believe that this line is not needed:
extratrees.block.planks.pinkivory=умнини
Maybe I'm wrong.

2017-06-04 16:09 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
> +# extratrees.block.planks.pinkivory=умнини
No. See screenshot
![image](https://cloud.githubusercontent.com/assets/1331559/26763298/558b19f2-4959-11e7-9ef2-6889bc20705c.png)

2017-06-04 17:21 UTC, lex1975 commented
Can you add RUS localization for https://github.com/KorDum/Binnie/blob/33f985c2e7c363554cdbd81a1f15d21e66ebea92/src/main/resources/assets/botany/lang/en_US.lang#L16-L123 ?

Probably not. I am not aware of the terms of design.

2017-06-04 17:51 UTC, KorDum commented
It's a pity. Ok, I'll try to translate myself =)

2017-06-05 06:43 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
> +# extratrees.block.planks.pinkivory=умнини
Please remove this change and I merge PR.

2017-06-05 07:12 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
>  extratrees.block.planks.pink ivory=умнини
This is wrong key.
Need without space. See screenshot above.

2017-06-05 07:14 UTC, KorDum requested changes

2017-06-05 07:14 UTC, KorDum commented on src/main/resources/assets/extratrees/lang/ru_RU.lang
> +extratrees.block.planks.pink ivory=умнини
This is wrong key. Need without space.
See screenshot above.

2017-06-05 07:24 UTC, merged